### ISSUE TITLE
On update nodes

### ISSUE THREAD

**Issue by b4zz4** [PongBuster/Blender-Addons#3]
Very good addon, I was looking for something like that a long time ago

```
Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops_nodes.py", line 22, in execute
    run_ops_without_view_layer_update(update_nodes,self,context,self.mode)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/utils_ops.py", line 29, in run_ops_without_view_layer_update
    func(*args)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops_nodes.py", line 358, in update_nodes
    m.generate(context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/nodes/Output/node_GPMorph.py", line 115, in generate
    generate_2d_morphs_with_pg(self.props,self.name,self.get_pass_index(),False,False,editor_props.mode)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 1537, in generate_2d_morphs_with_pg
    bpy.ops.gp2dmorphs.generate_2d_morphs(
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 81, in execute
    run_ops_without_view_layer_update(self.run,context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/utils_ops.py", line 29, in run_ops_without_view_layer_update
    func(*args)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 112, in run
    generate_morph_frames(self,context)
  File "/home/bazza/.config/blender/3.6/scripts/addons/GreasePencil2DMorphs-main/operators/ops.py", line 1675, in generate_morph_frames
    else:               self.reset_gp_layers_status(gp,multiple_layers,original_layer_locked=original_layer_locked,original_active_layer=original_active_layer,original_autolock=original_autolock)
  File "/usr/share/blender/3.6/scripts/modules/bpy_types.py", line 858, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'GP2DMORPHS_OT_generate_2d_morphs' object has no attribute 'reset_gp_layers_status'
Ubicación: /usr/share/blender/3.6/scripts/modules/bpy/ops.py:113

```

**Comment by rektuiemforameme** [comment]
Hi, glad you like my addon GP2DMorphs, but sorry you're having an issue with it. I think you posted this issue in the wrong repository. Mine is at https://github.com/rektuiemforameme/GreasePencil2DMorphs. No worries, happens to the best of us. I made [a new identical issue](https://github.com/rektuiemforameme/GreasePencil2DMorphs/issues/1). If you can, could you respond in that issue with any details on how this error happened? A screenshot of your node setup would be nice, as well as the node(s) that you had selected if you had Selected Only enabled.

**Comment by rektuiemforameme** [comment]
I posted on the new issue. Let me know if you still have any issues or questions
